Improve Row Evolution
xwikisas/application-analytics pull request #56
Opened 2023-10-11 09:47 UTC by Farcasut

Improved Row Evolution to support fields that contain % and added the bounce rate and exit rate fields to all the macros that support it.

2023-10-11 10:11 UTC, trrenty commented on application-analytics-ui/src/main/resources/Analytics/Code/Macros/RowEvolution.xml
> +      currentValue = currentItem[field] || 0;
For readability purposes, you could use `let`.

2023-10-11 10:11 UTC, trrenty commented on application-analytics-ui/src/main/resources/Analytics/Code/Macros/RowEvolution.xml
> +      // if the currentValue is a string that means that it co
Left over comment

2023-10-11 11:24 UTC, trrenty approved these changes

2023-10-11 12:05 UTC, oanalavinia requested changes

2023-10-16 07:23 UTC, trrenty commented on application-analytics-ui/src/main/resources/Analytics/Code/Macros/RowEvolution.xml
> +    const values = processChartValues(data, currentModal.find(SELECTORS.field).val())
missing semicolon here

2023-10-16 08:04 UTC, oanalavinia requested changes
Could you also add a screenshot?

2023-10-16 08:04 UTC, oanalavinia commented on application-analytics-ui/src/main/resources/Analytics/Code/Macros/RowEvolution.xml
> +    return currentValue;
Indentation, since this is inside the map callback function

2023-10-17 11:47 UTC, oanalavinia requested changes

2023-10-17 11:47 UTC, oanalavinia commented on application-analytics-ui/src/main/resources/Analytics/Code/Macros/RowEvolution.xml
> +      let result = $.map(data, function(currentItem) {
This isn't supposed to be indented. The next lines are because they are inside of the callback function

2023-10-20 06:39 UTC, oanalavinia approved these changes

2023-10-20 07:03 UTC, merged