Entry pages/Exit pages have extra entries #88
xwikisas/application-analytics pull request #89
Opened 2024-04-24 13:45 UTC by Farcasut

Filtering out the pages that should not be in the live data

2024-04-24 13:45 UTC, Farcasut commented
New Preview:
https://github.com/xwikisas/application-analytics/pull/89

2024-04-25 08:48 UTC, oanalavinia requested changes

2024-04-25 08:48 UTC, oanalavinia commented on application-analytics-ui/src/main/resources/Analytics/Code/Macros/EntryPagesJSON.xml
> +   #set ($discard = $filters.put("entry_nb_visits", ""))
indentation + single quotes

2024-04-25 08:48 UTC, oanalavinia commented on application-analytics-ui/src/main/resources/Analytics/Code/Macros/ExitPagesJSON.xml
> +  #set ($discard = $filters.put("exit_nb_visits", ""))
single quotes

2024-04-25 08:53 UTC, oanalavinia approved these changes

2024-04-25 10:07 UTC, merged